# Generated by Django 5.1.4 on 2024-12-22 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0004_alter_language_aa_alter_language_am_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/comments_images/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank.comment')),
            ],
            options={
                'verbose_name': 'Изображение комментария',
                'verbose_name_plural': 'Изображения комментариев',
            },
        ),
    ]
